jobs:
- job: build
  container: 
    image: squidfunk/mkdocs-material:4.0.1
    options: --entrypoint ""
  steps:
  - script: mkdocs build
  - script: mv site public
#  test:
#    docker:
#      - image: dkhamsing/awesome_bot
#        entrypoint: ""
#    steps:
#      - checkout
#      - attach_workspace:
#          at: .
#      - run:
#          name: Lint markdown files
#          command: awesome_bot --allow-dupe --allow-redirect --skip-save-results `find . -name "*.md"`
#  gh-pages:
#    docker:
#      - image: node:11.9.0
#    steps:
#      - checkout
#      - attach_workspace:
#          at: .
#      - run:
#          name: Disable GitHub Jekyll builds
#          command: touch public/.nojekyll
#      - run:
#          name: Install and configure dependencies
#          command: |
#            npm install -g --silent gh-pages@2.0.1
#            git config user.email "circle-ci@ukho.gov.uk"
#            git config user.name "circle-ci"
#      - add_ssh_keys:
#          fingerprints:
#            - "df:2f:bb:e8:16:52:04:e3:0a:8f:12:d7:2c:32:17:ae"
#      - run:
#          name: Deploy docs to gh-pages
#          command: gh-pages --dotfiles --message "[skip ci] gh-pages update" --dist public
#
#workflows:
#  version: 2.1
#  default_workflow:
#    jobs:
#      - build
#      - test
#      - gh-pages:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
#